# Generated by Django 3.1 on 2021-10-07 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0003_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='seniority_level',
            field=models.CharField(choices=[('Senior Level', 'Senior Level'), ('Intermediate Level', 'Intermediate Level'), ('Entry Level', 'Entry Level'), ('Internship', 'Internship')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
